package com.alex.webshop.repository;

import android.util.Log;

import com.alex.webshop.model.Category;
import com.alex.webshop.service.ConnectionEnum;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;

public class CategoryRepo {
    private final ConnectionEnum connectionEnum;

    public CategoryRepo(ConnectionEnum connectionEnum) {
        this.connectionEnum = connectionEnum;
    }

    public List<Category> getAllCategories() {
        List<Category> allCategories = new ArrayList<>();
        Category tempCategory;

        try (Connection con = DriverManager.getConnection(connectionEnum.getConnString(), connectionEnum.getUser(), connectionEnum.getPass())) {

            // The object used for executing a static SQL statement and returning the results it produces
            Statement statement = con.createStatement();

            // A table of data representing a database result set,
            // which is usually generated by executing a statement that queries the database.
            ResultSet resultSet = statement.executeQuery("SELECT Category.id, Category.name FROM Category");

            // Displaying results
            while (resultSet.next()) {
                tempCategory = new Category(); // skapas ny cat här

                tempCategory.setId(resultSet.getInt("id"));
                tempCategory.setName(resultSet.getString("name"));
                allCategories.add(tempCategory);
            }

        } catch (SQLException e) {
            e.printStackTrace();
            Log.d("webshopen", "Error reading categories from db");
        }
        return allCategories;
    }
}
